### ISSUE TITLE
MySQL Error: Illegal mix of collations

### ISSUE THREAD

**Issue by danascheider** [danascheider/tessitura-front-end#49]
When I load the homepage in my development environment (wired to the test API), I get 500 errors from the server that appear in the logs as:
<pre><code>71.238.42.189 - - [05/Oct/2015:00:52:50 +0000] "OPTIONS /organizations HTTP/1.1" 200 - 0.0006
2015-10-05 00:52:50 - Sequel::DatabaseError - Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=':
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/mysql2-0.4.1/lib/mysql2/client.rb:85:in `````_query'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/mysql2-0.4.1/lib/mysql2/client.rb:85:in `````block in query'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/mysql2-0.4.1/lib/mysql2/client.rb:84:in `````handle_interrupt'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/mysql2-0.4.1/lib/mysql2/client.rb:84:in `````query'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/adapters/mysql2.rb:78:in `````block in _execute'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/database/logging.rb:37:in `````log_yield'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/adapters/mysql2.rb:78:in `````_execute'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:34:in `````block in execute'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/database/connecting.rb:249:in `````block in synchronize'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/connection_pool/threaded.rb:103:in `````hold'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/database/connecting.rb:249:in `````synchronize'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/adapters/shared/mysql_prepared_statements.rb:34:in `````execute'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/dataset/actions.rb:921:in `````execute'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/adapters/mysql2.rb:195:in `````execute'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/adapters/mysql2.rb:154:in `````fetch_rows'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/dataset/actions.rb:802:in `````with_sql_each'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/dataset/actions.rb:812:in `````with_sql_first'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/dataset/placeholder_literalizer.rb:148:in `````first'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/model/base.rb:876:in `````block in def_finder_method'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sequel-4.26.0/lib/sequel/model/base.rb:313:in `````find'
	/home/dana/tessitura/lib/helpers/authorization_helper.rb:141:in `````valid_credentials?'
	/home/dana/tessitura/lib/helpers/authorization_helper.rb:34:in `````authorized?'
	/home/dana/tessitura/lib/helpers/authorization_helper.rb:115:in `````protect_communal'
	/home/dana/tessitura/lib/routes/filters.rb:31:in `````block in communal_auth_filter'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `````call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `````block in compile!'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `````[]'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `````block in process_route'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `````catch'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `````process_route'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `````block in filter!'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `````each'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:965:in `````filter!'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1083:in `````block in dispatch!'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `````block in invoke'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `````catch'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `````invoke'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `````dispatch!'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `````block in call!'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `````block in invoke'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/slogger-0.0.11/lib/slogger/request_logger.rb:25:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/rack-1.6.4/lib/rack/reloader.rb:44:in `call'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/gems/thin-1.6.3/bin/thin:6:in `&lt;top (required)&gt;'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/bin/thin:23:in `load'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/bin/thin:23:in `&lt;main&gt;'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/bin/ruby_executable_hooks:15:in `eval'
	/home/dana/.rvm/gems/ruby-2.2.3@tessitura/bin/ruby_executable_hooks:15:in `&lt;main&gt;'</code></pre>Notice this is an `OPTIONS` request coming in and getting this response. I remember having had this problem once before, but don't remember how I solved it.

It's worth noting that this request is not being made from the secure area, so it is probably not sending any credentials. My best guess as to what is causing this error is the following chain of events:
1. Request sent with credentials `btoa(':');`
2. Back end authorization helper parses the string `':'`
3. Authorization helper makes request to the database to identify logged-in user
4. Database barfs

I'll try to remember to update this issue with the ultimate solution to the problem.

**Comment by danascheider** [comment]
Duplicate
